### ISSUE TITLE
Missing UI controls

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#107]
### Expected Behavior
Some UI control elements are missing. (UpDown, Picture, Button, Radio, TreeView, ListBox, and others)
The most important (imho) are:
- [x] Text/Links
- [x] Button

**Comment by ewerybody** [comment]
You know you now can actually add ANY kind of made up element widget into Modules. Just like the HotStrings one is made! Of course, when there is a broader need for something (Which is not valid for HotStrings) it can make it into a2elements to be available for any module.

I mean of course Text & Button are out of question. But maybe TreeView might be too specific to really make it open for anything.

**Comment by ewerybody** [comment]
Voilà! One could probably also add Images and stuff with this.

The **TextField_AutoHeight** still needs some love tho. Not super happy with it yet. Could also be a simple PlainTextField. But I'd rather use this and improve it.

![label](https://cloud.githubusercontent.com/assets/218956/20196578/8eed73c6-a79b-11e6-8b8e-2d549066fb9f.png)
![label2](https://cloud.githubusercontent.com/assets/218956/20196580/90c892a2-a79b-11e6-85ee-6fd8cd5dd4e6.png)

**Comment by ewerybody** [comment]
Thought about the button: It should probably just execute Python code. You'd have the whole library at hand and could do anything really. What do you think?

I also improved the new element dialog! It's Incredible easy now.

**Comment by ewerybody** [comment]
@lipkau: Regarding you initial text: Changed it a bit. OK?
What's with the UpDown and Radio. These are actually "Variable-Controls" #43 right?

**Comment by lipkau** [comment]
> Thought about the button: It should probably just execute Python code. You'd have the whole library at hand and could do anything really. What do you think?

My opinion is that it should be aligned with the action of an element of type hotkey.
I think:
* both link to python function, and python can run code or call AHK functino (if at all possible. idk)
* both link to ahk function
* bot are possible, and developer must provide the "scope" in which the function is located [ahk|python]

**Comment by ewerybody** [comment]
I don't think it's so easy to trigger a function **within** another Autohotkey process.... But of course from Python you can easily just call ahk-scripts to run. I actually have some simple Autohotkey things that I run from the UI in /lib/cmds

I don't get the last line tho. Could you give me an example of what you want to do?

**Comment by lipkau** [comment]
### Explaining #3 
given the example:
```json
{
    "functionCode": "foo()",
    "key": "Win+Q",
    "label": "Execute foo()",
    "name": "foo_Hotkey",
    "typ": "hotkey"
  }
```

* by adding an attribute `"functionScope": "ahk"`, the Win+Q would execute the foo() function which is defined in <module>.ahk
* by adding an attribute `"functionScope": "py"`,   the Win+Q would execute the foo() function which is defined in <module>.py

**Comment by ewerybody** [comment]
Hmm I'm sorry. Do you have a use case for this?

I mean. The beauty of a2 is currently that everything just goes down into the runtime configuration. It's forward only.

We could call things on the a2UI through the QSingleApplication. So you call a2app.py with an argument and it's send to the running instance or creates a new instance. But I would not do that through the a2UI itself.

**Comment by lipkau** [comment]
So attaching an ahk function to a button click on the UI is difficult?
It would be fine for my current use case, as what I want to do is currently limited to grabing information and doing stuff on the file system

**Comment by ewerybody** [comment]
I'd go for the python calls first. You can just call a .ahk-file from there.
That'd be independent from the a2-runtime but do you need direct access to it?

**Comment by lipkau** [comment]
Well. what pops into mind when thinking about it is, that a button can be used:
* to open an extended UI (ie: btn `shedule indexing` of activ'Aid's _QuickChangeDir_)
* to do some kind of one time action (ie: I want to associate a file extension --> create `.reg` file and merge it)
* to run an action to set the value of a text field in the UI (ie: `Default` button next to the `path` control will set the path to "iexplore.exe" (UI to select browser to open something) --> where the default value is defined in the script)
* `more` button in activ'Aid's _TextAid_

**Comment by ewerybody** [comment]
1. & 4. For that stuff the UI is scrollable and resizable.
But we might have expandable groups! Would that be something?
2. & 3. Yea totally! 👍

**Comment by ewerybody** [comment]
Button done for now.
It takes the code put into the field and calls it with `exec`. What we can also do with this: Pipe some function or variable objects into it's scope. So The code can actually do something like act on the modules space directly and have it's path in a variable. 

Wip: I implemented the path already. See 5730abc

Closing this. Please open new issues upon demand. Thanks :] 👍
