### ISSUE TITLE
Use Windows10 Action Center for Notification

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#113]
### Expected Behavior
A script dev can show messages to the user in the Action Center.
a2 creates custom notification bubbles for Win > 10.

### Current Behavior
CNotification exposes a global `Notify()` function that creates better looking TrayTips. But not in the Win10 Action Center.

### Possible Solution
Enhance CNotification to have different behaviors by `if (WinVer >= WIN_10)`

**Comment by lipkau** [comment]
implemented with c8b4566e195f173173fd2ed310e6456dab72e911

**Comment by ewerybody** [comment]
Really nice btw! 👍

**Comment by lipkau** [comment]
thanks
