### ISSUE TITLE
Global function for modules to show debug messages

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#114]
### Expected Behavior
A user can define a global setting for whether debug messages should be displayed (and with what level?)
A module dev can use a global function for debug messages

### Possible Solution
Expose a global function that evaluates the user's debug settings and print the debug message accordingly.
* [ ] How are debug settings saved?
* [ ] should python code and ahk code write to the same debug stream?
* [ ] should ahk's `OutputDebug` be used?
* [ ] implement Debug Settings in the UI
* [ ] what debug levels make sense?
* [ ] document the debug levels for the module devs

### Related
* [Write to ahk's OuputDebug from Python](http://code.activestate.com/recipes/577040-use-debugview-utility-with-standard-python-logging/)

**Comment by lipkau** [comment]
* python debug messages have a different relevance than the ahk
  + python debug messages are important when:
    - dev creates a new UI for a module
    - a2 fails to write a ahk file
    - .
  + ahk debug messages are important when:
    - user is unsure is module is working correctly
    - give verbose information to the user
    - .

I have created a module ([DebugView](https://github.com/lipkau/debug.module/blob/develop/DebugView)) for the AHK debug messages.
By calling `DllCall("AllocConsole")` on initialization, a prompt (cmd.exe) is opened and the ahk runtime can write to it by `FileAppend  % "Hello World`n", *`.
It is not possible to define a global helper function to write debug messages, as the function will not be available to other modules if _DebugView_ is not loaded, and thus, a2 will fail to load (if a module is loaded that calls that function).
Possible implementations:
* every module is responsible to using `FileAppend` if it wants to write to the debug stream
* a2 offers the function as std lib (as currently implemented in [functions.ahk](https://github.com/ewerybody/a2/blob/master/lib/ahklib/functions.ahk#L698))

**Comment by lipkau** [comment]
@ewerybody : what is your opinion on this?

**Comment by lipkau** [comment]
RFC3164 (The BSD syslog Protocol) defines the following log levels:
1. Emergency: system is unusable
2. Alert: action must be taken immediately
3. Critical: critical conditions
4. Error: error conditions
5. Warning: warning conditions
6. Notice: normal but significant condition
7. Informational: informational messages
8. Debug: debug-level messages

_defined in [Table 2. syslog Message Severities](https://tools.ietf.org/html/rfc3164#section-4.1.1)_

I would propose to use a sub-set of these:
* **Debug** - Information that is diagnostically helpful to people more than just developers (IT, sysadmins, etc.).
* **Info** - Generally useful information to log (service start/stop, configuration assumptions, etc). Info I want to always have available but usually don't care about under normal circumstances.
* **Warning** - Anything that can potentially cause application oddities, but for which I am automatically recovering. (Such as retrying an operation, missing secondary data, etc.)
* **Error** - Any error which is fatal to the operation, but not the service or application (can't open a required file, missing data, etc.). These errors will force user (administrator, or direct user) intervention.

**Comment by ewerybody** [comment]
I actually don't know anymore if I took this here as a reference but:
**these exact levels** have been imlemented in the lib: [a2log.ahk](https://github.com/ewerybody/a2/blob/master/lib/Autohotkey/lib/a2log.ahk) 😃

Logging always happens to the very same file, Python AND AutoHotkey are writing there. In fact ANYTHING thats pushed to Pythons stdout ends up in the log file. Not all nicely level-formatted but added with a time stamp.

TBD are more special functions for the Console view. Its super limited right now, shows only the latest 4kb and only updates when you're watching it. Improvements for these should goto another issue :)

**Comment by ewerybody** [comment]
Ah actually there is an issue already: #203
