### ISSUE TITLE
onExit routines

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#115]
### Expected Behavior
A module is able to perform some cleanup OnExit().
Necessary for Module that Register stuff in memory outside of the runtime (`DllCall`)

### Current Behavior
a2 offers a script to register an "init" call, which is included (and executed) on script start.

### Possible Solution
Add a new element, that will make a2 execute that content on the Exit routine

**Comment by ewerybody** [comment]
@lipkau Is there a signal for Autohotkey that can trigger something on shutdown?
Otherwise I really don't know how we could solve this.
I mean creating the element and including the code is not the problem, right?

**Comment by lipkau** [comment]
It should be done just as the **init** element.

Create a new ahk file with one label **ExitRoutine:** append all **OnExit** UI elements and spend a "return"

I am working on a new exit routine for a2.ahk. (I am adding the functionality to call a2.ahk with parameters in order to send a command to a module from outside of the runtime)
I can then add a **gosub ExitRoutine** command.

**Comment by ewerybody** [comment]
Just as the init element? Ok. the init stuff is put into the function called `a2_init_calls()` so rather `a2_shutdown_calls()`? Or `a2_exit_calls()`?

I just wonder how we make sure this is triggered on any runtime shutdown. Like NOT from the UI (in which case we would know about it) but also killing it via Taskmanager or Tray Menu Exit ... Which we can actually capture! But also any `ExitApp` from within the runtime?

**Comment by lipkau** [comment]
https://autohotkey.com/docs/commands/OnExit.htm

**Comment by lipkau** [comment]
Ok. With ahk1.1.20+ we actually don't need to centralize this: 
> [v1.1.20+]: Any number of OnExit functions can be registered. If a label (subroutine) is also registered, the functions are called after the subroutine calls ExitApp

**Comment by lipkau** [comment]
@ewerybody : considering this finding... do you think we should let it up to the dev of a module to register the `OnExit()` in the module's ahk file **or** do you think it would be good for a2 to offer a collective exit routine?

**Comment by ewerybody** [comment]
Nice! We use 1.1.24 already!
Yea I didn't even know that there is something like that build into Autohotkey at all!

Hmmm currently we actually just **kill** the Autohotkey processes. I wonder if that triggers the OnExit routine anyway. Are you actively having problems not doing a cleanup in your modules?

**Comment by lipkau** [comment]
Not yet. But once I start my [WindowManager](https://github.com/lipkau/ol.modules/issues/12) (which will implement a lot of [NiftyWindows](http://www.enovatic.org/products/niftywindows/features/) features), I will.

further more, I am making some changes to **a2.ahk**:
* change to `#SingleInstance Off`
* register a `OnMessage(55555, "TriggerFromOtherInstance")`
* `OnExit()` with a handler to reload the script properly when `A_ExitReason == "reload"`

by doing this, a2.ahk can be called with parameters. if an other a2 instance is already running, the freshly called will sent the parameters to the other instance and kill itself.
And like that, it is possible to make a2 execute an action from cmd.exe (or the windows context menu, which is my goal)

**Comment by ewerybody** [comment]
Ah nice! Yeah I was actually looking for a way to achieve this! Killing the Autohotkey instances was actually my last resort to fix having multiple ones running! 👍 Awesome!

**Comment by lipkau** [comment]
is implemented by #121

**Comment by ewerybody** [comment]
OK. a2.ahk now calls work. We just need interface for it like with the init elements.
