### ISSUE TITLE
UI element String needs option for Password

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#116]
### Expected Behavior
Dev has en UI element he can use to request the user to input a password where the characters entered are hidden

### Current Behavior
All strings are shown

### Possible Solution
* [x] Add a flag for the string to be "hidden"
* [ ] How to store such an entry? in variables.ahk as plain text is a big security risk
  + maybe use a reversible encryption algo, that python an AHK have in common **(AES)**.
     - UI can encrypt the string before storing
     - AHK can encrypt the string

### Related
* Availbale cyphers in AHK
    - [LibCrypt](https://github.com/ahkscript/libcrypt.ahk)
    - **incomplete implementation** [ahk cryptography class](https://autohotkey.com/board/topic/67155-ahk-l-crypt-ahk-cryptography-class-encryption-hashing/)
    - [Sean's code](https://autohotkey.com/board/topic/21913-aes-encryptdecrypt-of-a-file-in-wxp-or-higher/page-2#entry388246)
* Python cypther (AES)
   - [encrypt-decrypt-using-pycrypto-aes-256](http://stackoverflow.com/questions/12524994/encrypt-decrypt-using-pycrypto-aes-256)

**Comment by ewerybody** [comment]
Ok. password mode can be checked now.
But I really don't know about the encryption thing. I mean there is no way we can make this bulletproof. Might be just having it NOT in plain text is a little better already and we need a warning for the user that this is only for convenience to not put sensitive data into this!

To make it better we might ask the user for a master password thats saved nowhere and used to decrypt the saved string.

**Comment by lipkau** [comment]
That is the goal with something like a AES encryption. 
Fully reversible, secure, user can provide password for encryption, available in both scopes (I must confess, I am yet to find the AES implementation for ahi).

**Comment by lipkau** [comment]
I think it is important for a2 to provide easy-to-use solutions for the module devs.
If a module dev needs to ask the user for a password, and a2 does not provide a comprehensible way for him to do this in a secure manner, he might store the password in clear text.
Also, we cannot assume all module devs will add the information to the user, that the password will not be saved in an _ultra secure vault_ and that he should not enter sensitive information

**Comment by ewerybody** [comment]
OKe as one part of this is implemented and the other part is not really a focus of this project now I'd put it on the backlog.
Good starter issue maybe 😉 cheers!
