### ISSUE TITLE
Use same hotkey across multiple modules

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#118]
### Expected Behavior
The customer can have 2 different actions (by different modules) for the same hotkey, if he chooses to.
_Or: a2 should not crash if a module registes a hotkey that is already in use_

A dev can only use a hotkey conditionally (ie: [SetTimer](https://github.com/lipkau/ol.modules/blob/feature/SetTimer/SetTimer/SetTimer.ahk#L35) only uses the mbutton if the cursor is over the clock in the taskbar) and by doing that, keeps any other module from using it.

### Current Behavior
A module can use a Hotkey in 2 ways:
1. define it in the a2UI and thus get it generated in hotkeys.ahk
    * downside: if another module registers the same hotkey, a2.ahk will fail to load
2. define it in the .ahk included by the module
    * downside: user is unable to change it/disable it (unless module dev implements a setting in the UI (for disabling a hotkey) or implement a similar way the hotkeys where defined in activAid)

### Possible Solution
Instead of writing the hotkeys.ahk file inline (as is):
```
mbutton::SetTimer.Execute("overClock")
mbutton::VolumeManager.execute("toggle", "Shell_TrayWnd")
```
it could be written as a block which can be appended by all modules using that hotkey:
```
mbutton::
    SetTimer.Execute("overClock")
    VolumeManager.execute("toggle", "Shell_TrayWnd")
return
```

**Comment by lipkau** [comment]
@ewerybody: what do you think?

**Comment by ewerybody** [comment]
Yea thats the plan! :]
Also vice versa: have multiple hotkeys triggering the same function.

The user should be notifyed that setting/activating this hotkey, activating this module will cause a conflict (also with standard Windows functions). There will be a dialog that lets you decide if you want to override or combine the functionality.

**Comment by ewerybody** [comment]
see #15

**Comment by lipkau** [comment]
oh. my bad. didn't see that issue.
any idea on when we can work on this?

**Comment by ewerybody** [comment]
Pchew.. no not a clue. Might be on the weekend? Is this a priority?

**Comment by lipkau** [comment]
no. not critical.
would be good for my modules but not a blocker.

however my opinion is, that is should be in aplha

**Comment by ewerybody** [comment]
@lipkau: Hey is this done now?
I think we would need some feedback in the hotkey dialog. But apart from that?

**Comment by lipkau** [comment]
LGTM! 🎉 

```ahk
; a2 hotkeys.ahk - Don't bother editing! - File is generated automatically!
#IfWinActive,
#+a::a2UI()
capslock::BlockCapsLock_callback()
#q::dynSnips.ShowMenu()
^+h::ExplorerReplace.ShowGui()
#s::urlShortener.Execute()
#h::AutoCorrect_AddCustom()
#f12::KeepAlive.Toggle()
^#t::SetTimer.Execute("show")
mbutton::
	SetTimer.Execute("overClock")
	VolumeManager.execute("toggle", "Shell_TrayWnd")
return
wheelup::VolumeManager.execute("+", "Shell_TrayWnd")
wheeldown::VolumeManager.execute("-", "Shell_TrayWnd")
volume_up::VolumeManager.execute("+")
volume_down::VolumeManager.execute("-")
volume_mute::VolumeManager.ChangeVolume("toggle")
!l::gtranslate()
+#f10::ListVars
+#f12::InspectObject()
#+f11::DebugView_Write("Howdy, mate")

#IfWinActive, ahk_class ConsoleWindowClass
^c::Send, {enter}^C{BackSpace}
^v::SendInput {raw}%clipboard%
^a::commandLine_selectAll()
```

**Comment by ewerybody** [comment]
the notification will happen along with the hotkey validation. I'll close this for now.
