### ISSUE TITLE
Handle of "universal settings"

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#119]
### Expected Behavior
User can enter preferences that are not module specific. 

### Current Behavior
Settings can be:
1. on `a2settings_view`
  + `a2settings_view` has a limited space
  + settings can be of different types, will be cluttered and messy
2. **[will not be done]** ~module [Proxy](https://github.com/lipkau/ol.modules/tree/develop/Proxy) injects settings so that all modules can use it~
  + ~theme specific settings~
  + ~settings are not included is module or groupbox is not active~

### Possible Solution
Make a `Advanced Options` module where settings can be saved

Some settings I know might be useful:
* Image Editor path
* Text editor path
* run as elevated
* see ac'tiveAid for more

**Comment by lipkau** [comment]
as agreed with @ewerybody: **a2settings_view** should include all global settings.
If the lists grows to large, the view should allow the user to search/filter (like chrome settings).

**Comment by lipkau** [comment]
This should implement the Proxy@ol.modules in the same way they where by the module:
```
Settings.Proxy := [object]
Settings.Proxy.Enabled := [bool]
Settings.Proxy.Address := [string]
Settings.Proxy.Port := [string]
Settings.Proxy.Type := [enum(HTTP|Socks4|Socks5)]
Settings.Proxy.Authentication := [object]
Settings.Proxy.Authentication.Enabled := [bool]
Settings.Proxy.Authentication.Type := [enum(Basic|NTLM)]
Settings.Proxy.Authentication.Username := [string]
Settings.Proxy.Authentication.Password := [string]
```

**Comment by lipkau** [comment]
Module [DebugView@debug.module](https://github.com/lipkau/debug.module) implements a Setting `Setting.Debug.Enabled := [bool]` ([here](https://github.com/lipkau/debug.module/blob/develop/DebugView/DebugView.ahk#L10)).

Should this also be part of the a2settings.view?
This Settings is used by the global helper function [WriteDebug](https://github.com/ewerybody/a2/blob/master/lib/ahklib/functions.ahk#L698)

**Comment by ewerybody** [comment]
As Advanced Settings tab is already done with some of the suggestions and lots of room for more and there is a Proxy option the the page I'd close this.

Regarding the debug-view: Options to toggle what log-level messages are shown are part of #203 already. :)
