### ISSUE TITLE
[Help] a2UI element label

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#120]
### Expected Behavior
The UI element **label** allows for html.
I was not able to use it with `<img src="modules/ol.modules/Foo/resources/pic.jpg">`, but it never loads.
What is the relative path?

**Comment by ewerybody** [comment]
Oh good question. Never tried it yet. probably the ui folder. I would actuallty not advise to do so: The module path is meant to be arbitrary and not next to the ui path like in dev.. hmm :/

**Comment by ewerybody** [comment]
But yeah it works! 
![screenshot_20161209181000](https://cloud.githubusercontent.com/assets/218956/21057632/c4966d10-be3a-11e6-8a88-9d9bbce15336.png)
with the string:
`<img src="../modules/erix_modules/asd/asd.png">`

The thing is: It doesn't seem not work with any image. At least not any png. The a2.png from res for instance refused to work like that :/ dunno why.

**Comment by lipkau** [comment]
hm.
if you change modules from the default path, that will no longer work.
Ideally, each module view would have a relative path to the module's root

**Comment by ewerybody** [comment]
Yea that was my [point](https://github.com/ewerybody/a2/issues/120#issuecomment-266063267) ;]
I could look into the label text and replace stuff! How about that?

We could have common variables that we use throughout the framework.
`%module_path%` ?

**Comment by lipkau** [comment]
oh. interesting. let's go for it
too bad that can't be done in ahk the same way

**Comment by ewerybody** [comment]
```
module_path: %module_path%
<img src="%module_path%/asd2.png">
```
![label_imgs](https://cloud.githubusercontent.com/assets/218956/21058556/bf01704e-be3e-11e6-9cbf-f4747f045f90.png)

Works even with the backslashes!! I thought I'd need to swap them
