### ISSUE TITLE
Register URI schema for App

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#122]
continues #79 

### Expected Behavior
a2 can execute a command if a URL is called

### Current Behavior
n/a

### Proposition
Register a2:// Schema to execute a2.

### Limitations
1. URi Schema must be register as Admin
2. Schema can only call 1 target (not python **and** ahk)

### Possible Solution
1. register Schema
  * [ ] a2.exe checks if it has admin rights to make the merge
  * [ ] a2.exe asks for elevation if not already
  * [ ] a2.exe merges .reg with the Schma
  * [ ] a2.exe does not register schema if user doesn't give admin permissions
     + what will happen when user opens url with app schema without having it registered?
2. What target to register?
  * [x] Python
     - `a://module/add/?url=https://github.com/XX/YY/archive/BRANCH.zip` install a new modulePack from an internet source
     - `a://module/activate/MODULENAME` activate a previously inactive module (I plan using this in the wiki articles of modules that depend or extend other modules)
  * ~AHK~ **will not be done**

**Comment by lipkau** [comment]
@ewerybody : opinion on item 2. ?

**Comment by ewerybody** [comment]
This should go through the Python a2app. The a2 runtime should not care about administration whatsoever. Otherwise we have 2 spots dealing with similar stuff again.
We can call Autohotkey stuff through Python anyway but we can hardly make changes to the ui via Autohotkey.

**Comment by lipkau** [comment]
we were discussing the elevation of the a2.ahk runtime in #117.
That would already have an implementation of admin permissions. so the a2app would be "the 2 spot dealing with similar stuff"

but indeed, a2.ahk would not be able to download a modulePack and show this in the UI. or can it?

**Comment by ewerybody** [comment]
The scheme should **always** be from the ui to the runtime. And never backwards. Or as seldom as ever possible. All this administration stuff is to be handled by the a2ui.

In theory you could of course create folders, JSONs and db entries by any means but this really gives me headaches already!!! Please don't!

**Comment by lipkau** [comment]
fine by me. Actions I see the a2UI should support in the schema:
* `a://module/add/?url=https://github.com/XX/YY/archive/BRANCH.zip` install a new modulePack from an internet source
* `a://module/activate/MODULENAME` activate a previously inactive module (I plan using this in the wiki articles of modules that depend or extend other modules)

Also, I think it is important that the a2.ahk is the one that registers the schema in the registry.
reason: if a user opens a "getting started" documentation with links to install a module (via schema), it might be the case that the a2ui was never started before
