### ISSUE TITLE
Help: usage of Button element

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#123]
### Expected Behavior
I am able to add a `button` element to the a2UI.
When the button is pressed, it executes the function `foo()` in "modules/ol.modules/moduleName/moduleName.py"

### Questions
* How is "modules/ol.modules/moduleName/moduleName.py" loaded?
* What must I add put in the button's field "Python Code"?

**Comment by ewerybody** [comment]
We have a Wiki page about this: https://github.com/ewerybody/a2/wiki/Button-element
Which is also available via the Help on the very element :]

![button_help](https://cloud.githubusercontent.com/assets/218956/23791811/c394eaae-0584-11e7-83b7-63e8494124a3.gif)

Is there still something missing?
