### ISSUE TITLE
Allow empty UI hotkey element

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#124]
### Expected Behavior
A module dev is able to provide _hotkey_ elements in the UI which are disabled by default and have no value.

_I have a module ([VolumeManager](https://github.com/lipkau/ol.modules/blob/develop/VolumeManager/a2module.json#L129)), in which I allow the user to specify custom hotkey for actions. However, I don't want to define any defaults._  
_This is fine as long as the Group element is disabled. If enabled, a2 would crash, as the default key <kbd>WIN+F</kbd> would already be assigned in the script_

### Current Behavior
The _hotkey_ element does not allow for _empty_ value

### Possible Solution
Allow _hotkey_ to be empty, and consider this when generating the `hotkeys.ahk` file

**Comment by ewerybody** [comment]
Will be done through #15

**Comment by lipkau** [comment]
Great. Thanks

**Comment by ewerybody** [comment]
Yea might be that could be done even without the full blown new fancy pants Hotkey Dialog. But I'd like proper feedback for this anyway.
