### ISSUE TITLE
Compilation script of a2starter.ahk

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#126]
### Expected Behavior
A dev can make changes to a2starter.ahk.
When the dev needs to compile, the repo offers a config set, which supports **[Compile_AHK II](https://autohotkey.com/boards/viewtopic.php?f=6&t=16061)**.
This allows the dev to compile the script, place it in the correct directory, with the correct name and with the correct icon(s)

### Possible Solution
* [ ] create a .ini file with the configuration
* [ ] add the configuration to the file as comment block

**Comment by lipkau** [comment]
@ewerybody, what is your take on this?

**Comment by ewerybody** [comment]
@lipkau: sorry I think we were talking about this before but didn't write anything down so far.
I use these and they work fine so for me:
`a2\lib\batches\a2starter_build.bat`
`a2\lib\batches\a2ui_build.bat`
Is there anything missing?

**Comment by ewerybody** [comment]
we have working build scripts for
- [x] the whole package and
- [x] the installer (with icon 😃)
