### ISSUE TITLE
a2 module tutorial

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#127]
### Expected Behavior
a2 has a comprehensive tutorial on "how to create  your own modules"

### Current Behavior
n/a

### Possible Solution
* a wiki page with details and screenshots describing the flow on how to create a module using the a2 dev gui
* wiki pages with examples on how to implement stuff in a2. The following occurred to me:
  - [ ] a modulePack with sample modules, where these have varying degree of complexity and use different techniques
    + draw back: a lot of effort to come up with modules that make sense and are good examples
  - [ ] add a section on the documentation of each "real" module, that describes what (and what parts) can be used as example to implement something in a2
    + I described this with a sample for the documentation here: https://github.com/lipkau/ol.modules/issues/35

**Comment by lipkau** [comment]
@ewerybody : what is your opinion on this?

**Comment by ewerybody** [comment]
I'd love to also have a video about this!!
