### ISSUE TITLE
new translation module

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2#133]
### Expected Behavior
Best would be if it would be as easy as LeoToolsTip used to work. Select a thing, hit a hotkey, no matter if its english or german it gets translated.

### Current Behavior
They changed the API again and actually seems they don't want externals to use their stuff anyways: https://dict.leo.org/forum/viewGeneraldiscussion.php?idThread=13869&idForum=4&lang=de&lp=ende

### Possible Solution
It was pretty good but well, I don't care there are other means of translating stuff.: We could hack google translate with this for instance: https://autohotkey.com/boards/viewtopic.php?f=5&t=21105&p=101591&hilit=translation#p101591

Using their actual translation API costs money :/
I was also looking into downloading a translation dictionary to use that offline. That'd be neat wouldn't it?

dict.cc offers something: But everyone would need to download it himself: http://www1.dict.cc/translation_file_request.php

ideas?

**Comment by ewerybody** [comment]
@lipkau

**Comment by lipkau** [comment]
I am in favor of using google translator:
https://ctrlq.org/code/19909-google-translate-api

**Comment by lipkau** [comment]
you could use something like this:
```
translate(srcTxt, srcLng, transLng)
{
    ApiURi := "https://translate.googleapis.com/translate_a/single?client=gtx"
    ApiURi .= "&sl=" srcLng
    ApiURi .= "&tl=" transLng
    ApiURi .= "&dt=t"
    ApiURi .= "&q= " uri_encode(srcTxt) ; https://autohotkey.com/board/topic/75390-ahk-l-unicode-uri-encode-url-encode-function/

    Headers := "Content-Type: application/json`n"
    Headers .= "Referer: https://github.com/lipkau/ol.modules`n"
    Headers .= Settings.Proxy.Authentication.Username && Settings.Proxy.Authentication.Password ? "Proxy-Authorization: Basic " Base64Encode(Settings.Proxy.Authentication.Username ":" Settings.Proxy.Authentication.Password) : ""  ; TODO decrypt pw?

    Options := "Method: GET`n"
    Options .= "Charset: UTF-8`n"
    Options .= Settings.Proxy.Enabled ? "Proxy: " Settings.Proxy.Address ":" Settings.Proxy.Port "`n" : ""

    WriteDebug("HTTPRequest request HEADER:", Headers, "debug", this.moduleName)
    WriteDebug("HTTPRequest request Options:", Options, "debug", this.moduleName)

    HTTPRequest(ApiURi , response, Headers, Options)

    WriteDebug("HTTPRequest response HEADER:", Headers, "debug", this.moduleName)
    WriteDebug("HTTPRequest response BODY:", POSTdata, "debug", this.moduleName)

    RegExMatch(response, "\[\""(.+?)\""", match)
    return match1
}
```

**Comment by lipkau** [comment]
shouldn't this issue be moved to a2.modules?

**Comment by ewerybody** [comment]
Sure. But discussion can happen here as long as there is nothing planned. I'd like to keep the planning here and have specific issues on the modules there. Is that ok? What would you say?

**Comment by lipkau** [comment]
I don't mind it being discussed here.
I just prefer (and that's how I do it with my module Pack) to discuss it where the implementation happens.

I was also thinking about the "projects" in a github repo... if that is something we could use

**Comment by ewerybody** [comment]
Alright. handed off to a2.modules https://github.com/ewerybody/a2.modules/issues/10
