### ISSUE TITLE
nicer Hotkey dialog

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2#15]
So there are plenty of ideas to make this dialog much cooler. Actuallty I ran ahead of the least possible version already by making it a floating window with colorful validator functionality... but writing the keys of course is stupid. I'd like to:
- have the writing autocompleted?
- just press the shortcut and capture the input!
- have a map of available keys (probably optional)
- see conflicting keys right away
  - also see standard windows functions that would be overridden
- ~ option to pass original hotkey function [or other features](https://autohotkey.com/docs/Hotkeys.htm#Symbols)
- option to merge functions to avoid hotkey conflicts

**Comment by ewerybody** [comment]
So there are different things that can happen with the **double Hotkey**. The dialog should:
* show you that there is a conflict
* not allow you to proceed without making a decision
* offer to trigger both actions
  * which would result in writing the code in `hotkeys.ahk include` with linebreaks and a return.
  * also on different scopes show you that it overrides the original global hotkey and include the original global line of code
* offer to disable the conflicting hotkey or goto the module with the conflict

**Comment by lipkau** [comment]
That would be awesome!

**Comment by ewerybody** [comment]
Damn, thats quite a piece of work ... but getting there :]

![screen_22](https://user-images.githubusercontent.com/218956/29934223-a4722fe0-8e7a-11e7-9149-c56af88b0084.png)

**Comment by lipkau** [comment]
Is this dynamically generated according to the keyboard layout chosen by the user?

**Comment by ewerybody** [comment]
Nope. Some manual labor. But I want to make it as dynamic as possible in the future and users can choose what keyboard they have or even edit theirs (Numpad block off for instance)

**Comment by lipkau** [comment]
This C/C++ repo are examples on the keyboad layout in external files:
https://github.com/AlterX76/VirtualKeyboard

**Comment by ewerybody** [comment]
![hotkeyboard_dialog](https://user-images.githubusercontent.com/218956/35507645-c5731184-04ed-11e8-9ff9-e6be19ce8fc5.png)

Pcheeew 😃 getting there. Size is fixed and always minimized now.
TBD:
- [ ] fix extra buttons being connectd properly
- [ ] try to decrease left/right padding of main key block
- [ ] show mouse/numpad widget if Hotkey has according button but showing is disabled
- [ ] Ctrl+Click on modifier to toggle both left/right keys
- [ ] show other hotkeys in same scope

**Comment by ewerybody** [comment]
![a2_keyboard_dialog](https://user-images.githubusercontent.com/218956/35699475-7c09d91a-0790-11e8-8a75-96b79e03748e.png)

**Comment by ewerybody** [comment]
I gonna close this monster 👹 and create follow up issues ...
