### ISSUE TITLE
Create an installer

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#154]

**Comment by ewerybody** [comment]
thanks to @lipkau we have some thing to start here: https://bitbucket.org/ArmstrongJ/lightning-python/src
didn't disassemble yet tho.

**Comment by ewerybody** [comment]
I'm stuck with this msi stuff :(
Maybe we should stick to what we do and offer a AHK-based installer!?

Looking at [AHK itself...](https://github.com/Lexikos/AutoHotkey-Release/blob/master/installer/tools/UPDATE.bat) they use the 7zip sfx stuff to create a packed executable. The only 7zip package that I found that actually HAS this stuff seems ancient: 

I made a test and got it running. One problem is: This seems to always popup the UAC. Which we actually don't need. But we can try this at least. :)

build script needs to do:
- [ ] run default build
- [ ] compile installer script to `setup.exe`, add to package
- [ ] zip to .7z
- [ ] bundle installer.exe

the installer script itself:
- [ ] check/taskkill running a2/a2ui from default a2 path
- [ ] cleanup default a2 path, keep `_ user_data_includes.ahk`
- [ ] copy archive contents to default a2 path
- [ ] restart a2/a2ui

This should actually just be an entrypoint. In the end I'd love the a2ui to be able to update it all by itself and even clean it all up again. But thats another issue ...

**Comment by ewerybody** [comment]
More info for the record:
* [Autohotkey itself](https://github.com/Lexikos/AutoHotkey-Release/blob/master/installer/tools/UPDATE.bat#L15) uses a 7zip self extracting archive!.

* One can do things like ResourceHacker does right with **VisualStudio**. thanks to [this post](https://stackoverflow.com/a/2886735/469322) ... Of course like changing the **icon** but also editing away the FileDescription, Version Nr and stuff.. <br>(The `.sfx` needs to be renamed to `.exe` for editing tho)

* By default the 7zip self extracting archive causes UAC to popup! This is nasty and causes the restart of a2 or a2ui to be elevated as well. I tried to Run with lowered priveliges but the [Autohotkey RunAs command](https://autohotkey.com/docs/commands/RunAs.htm) does not seem to be working that easy!  ([see](https://www.autohotkey.com/boards/viewtopic.php?p=259612#p259612)).

* Getting away the need for UAC we need to add an according manifest to the `.sfx` file! See [this awesome post](https://stackoverflow.com/a/20870775/469322). This can be done with `mt.exe` from [Windows SDK](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk). [Thanks to this](https://stackoverflow.com/a/1424078/469322).

Posted also [here](https://sourceforge.net/p/sevenzip/discussion/45797/thread/28174d35).

Now the installer builder does just the same as before and just runs right away without UAC.
A nice followup task would be to actually change the executable details to have the correct version Nr and to be from us.
