### ISSUE TITLE
offer uncompressed executables

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2#176]
### Current Behavior
Some anit-viruses report problems with the a2-executables (`a2.exe`, `a2ui.exe`)
That might be due to the `/mpress 1` setting for building these.

### Possible Solution
Provide a package with uncompressed executables.

**Comment by ewerybody** [comment]
Darn! The unpacked ones are double the size but do not appear as clean either: https://www.virustotal.com/#/file/11bb02a89a174ed7a37960dd12168130366ecbcd75e7791c498996b87dd76235/detection 

ffing heuristics scan ... 🤦‍♂️

I wonder: can we do without these at all? We have everything on board.

**Comment by ewerybody** [comment]
however I'll upload the ones without `mpress` which seem a little "less dangerous" ... (who uses Antiy-AVL, Trapmine, Jiangmin to check for viruses?!?!)

**Comment by OlafHaag** [comment]
I already received an answer from avast after sending in the portable a2 archive in for clearance yesterday.
I hope this also resolves any issues with future versions of a2 portable and avast virus scanner.

> Hello,
> Thank you for reporting this false positive.
> Our virus specialists have now cleared its reputation in our database.
> With URLs this change should be instant, but it might take up to 24 hours with files.
> For future reference you might also find the following article to be useful: [Avast Clean Guidelines](https://support.avast.com/en-us/article/228/).
> 
> Best regards,
> Avast Customer Care

**Comment by OlafHaag** [comment]
Dang! Avast Antivirus still acts up on a2app.exe and moves it into containment (cause: _Win64:Trojan-gen_).
FYI: if this error happens to anyone else, it's probably their antivirus software:
> ---------------------------
> a2ui.ahk
> ---------------------------
> Error:  Failed attempt to launch program or document:
> Action: <a2app.exe>
> Params: <>
> 
> Specifically: Zugriff verweigert
> 	Line#
> 	075: WM_SETFONT := 0x30
> 	001: if (a2_startup_tool_tips == "true")  
> 	002: tt(a2_title, 0.5)  
> 	004: ui_path = %A_ScriptDir%\..\ui\
> --->	005: Run,a2app.exe,%ui_path%
> 	007: Sleep,500
> 	010: Return
> 	001: SetTitleMatchMode,2
> 	002: a2_title := "a2 0.0.11 alpha"
> 	012: Exit
> 	013: {
> 	015: eZttDelay := 30
>
> The current thread will exit.

**Comment by ewerybody** [comment]
Avast is [not the only one on virustotal.com](https://www.virustotal.com/gui/file/49022a5430935ea0ffcfd6e1799d3244610019fc524978257b102bae584eee60/detection).

Although [I explicitly tell PyInstaller to not use UPX compression](https://github.com/ewerybody/a2/blob/master/lib/batches/build/_build_py_package.bat#L55). 🤨

Can You try building and try checking the same on virustotal?

**Comment by ewerybody** [comment]
I just built on my office machine and submitted the `a2app.exe` [which now looks a little different on Virustotal](https://www.virustotal.com/gui/file/ec2526e592caa8bca58525d1f02bde77f1aa80262182dca683866f2925262784/detection).

Maybe we should build on ALL the machines and take the executables from the one that yields a better looking picture on VT 🤦‍♀️ .... (that's a joke)

**Comment by ewerybody** [comment]
Here is a comment about reporting false positives:
> https://github.com/hillu/local-log4j-vuln-scanner/issues/7#issuecomment-992583319
