### ISSUE TITLE
maybe add to your requirement which Auto Hotkey version is used

### ISSUE THREAD

**Issue by sl5net** [ewerybody/a2#185]
maybe add to your requirement which Auto Hotkey version is used

thanks

**Comment by ewerybody** [comment]
Hey Sebastian! True. We just state [somewhere](https://github.com/ewerybody/a2/wiki) that we make use of the latest Autohotkey_L. Yeah that could be more prominent and explicitly placed. 👍

Currently the binary Autohotkey executable is part of the package. So technically one will be on the save side anyway. But it might be part of a dev setup script that also checks for the up-to-dateness of Python 3, Qt for Python and PyInstaller...

What do you mean with `your requirement`?

At first I'll do the following:
- [ ] script to assemble versions of software used and generate text snippet
 - [ ] place to the main README.md
 - [ ] place into description of releases
