### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2#187]
I don't see instructions on how to uninstall, i guess it's just the directory structure 
[USER]\AppData\Local\a2
that needs to be deleted.
However, maybe it would be nice to put that info somewhere.
Or also add a script to do this with a click from the UI.
Or, what i think would be the most appropriate, make A2 appear in the apps list, where it could be uninstalled from.

**Comment by ewerybody** [comment]
Oh Yes! Good reminder! For a2 I actually never thought of uninstallation so far :D
But true: There should be one convenient and clean way to do this!

For completeness:
* %USERPROFILE%\AppData\Local\a2
* %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\a2.lnk
* %USERPROFILE%\Desktop\a2ui.lnk

Last 2 of course only optional if set. But well, not hard to do.
- [ ] build uninstaller
- [ ] add to Windows Installed Apps list

**Comment by ewerybody** [comment]
Just a reminder for this: One can create and run batch scripts that are able to delete themselves see https://stackoverflow.com/a/20333152/469322 nice!

**Comment by ewerybody** [comment]
OK. The installer is done.

Meanwhile I'm not so sure about this "Windows Installed Apps list" 😐 That's again digging deeper into the system. Where we actually want a slim installation. Maybe this can be optional?

But anyway. What now needs to be done is:
- [ ] create uninstaller in build process
- [ ] connect in Start Menu options
