### ISSUE TITLE
UI: Symbols/buttons are too small to recognize on a 4k display ~LowPrio

### ISSUE THREAD

**Issue by Rylinn** [ewerybody/a2#189]
**FOUND:**

Symbols are too small to recognize on a 4k display.
It's been a while since I set something up in A2 and it was time to install it on my new laptop..so that's how I faced this issue when I couldn't find the button.

**Build:**
- Prerelease 0.0.6

**STR:**

- use an 4k monitor
- open A2
- try to find the 3 dotted symbol

**RESULT:**

Observe that it is hard to recognize.

**EXPECTATION:**

Should be more visible/ scaled up.

**General Info:**
I <3 A2!

**Comment by ewerybody** [comment]
Hey @Rylinn ! Thanks so much for the report! :)
Could you provide me with some more info plz?
* the actual resolution you have
* the UI scale factor if set different than 100%
* did you open completely new on your laptop or did you have older a2 settings that you used?
* can you provide a screenshot?

You know there actually IS a ui scaling feature built in already but its not well tested and not with 4k displays. The initial size of the a2 ui-Window is also not set accordingly. There is only 1 initial size.

**Comment by Rylinn** [comment]
Hey, thanks for your fast reply @ewerybody ! :)
No worries, I can still work with A2, it is not blocking me in any way. It was only confusing the first 10minutes hehe

Oh I thought that I've attached an image. Will be attached to this comment.

Info:
• Resolution: 3840 x 2160
• Scaling.. okazz it is set to 250% (recommended). On 100 everything else on windows with this resolution will look off
• I've used totally new settings, just redid the old scripts by having a peek on it. (all new)

I'll test it and provide as much info regarding the build in ui scaling in case I face another issue like this. ;)

![a2_symbols_4k](https://user-images.githubusercontent.com/6690967/76701420-458fe180-66c1-11ea-9a0e-3ffab7f52060.PNG)

**Comment by sirtet** [comment]
I just installed 006 with no older version on before, and i get no scaling:
![image](https://user-images.githubusercontent.com/3509308/76707607-ea75e300-66f0-11ea-8cd4-f41e094ad7a1.png)

**Comment by ewerybody** [comment]
Hey everyone! No worries thats pretty much on topic.
I actually got the same here (on my laptop) and noticed that it got bad after the update.
I'll look into the regression but also I'll check for the initial scale setting.

- [ ] icons seem unaffected by ui scale setting
- [ ] test and implement resolution & scaling aware initial window size setting

**Comment by ewerybody** [comment]
Alright! I found a solution for:
- [ ] the modules list,
- [ ] the more buttons (💬 the three dotted)
- [ ] the module source widgets
but nothing so far for the menu items. I'm kinda baffled here. I was trying to investigate there first and it actually seems impossible via stylesheet. Whatta bummer. the other ones were fairly easy.

I'll close this one and add 2 backlog issues for
- initial a2 window scaling (opening a2 for the first time ever)
- change the menu item icons size accordingly to stylesheet.
