### ISSUE TITLE
Module 'gtranslate' crashes when enabling it

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2#190]
![image](https://user-images.githubusercontent.com/3509308/76707736-1e053d00-66f2-11ea-9245-fd29babbf38f.png)

### Steps to Reproduce
1. Install A2
2. enable gtranslate
3. see the crash report

* Version used: 0.0.6
* python: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
* Win 10_64

**Comment by ewerybody** [comment]
Ah alright! Dang, thats already been solved! [See](https://github.com/ewerybody/a2.modules/blob/master/gtranslate/gtranslate.ahk) I just need to deploy a new version of a2.modules.

btw: You can actually <kbd>Ctrl</kbd>+<kbd>C</kbd> on an error-popup like that to get the whole content. No need to make a screenshot! ;)

**Comment by ewerybody** [comment]
Alright. I pushed a new version of **a2.modules** you know how to update right?
Can you check? @sirtet?

**Comment by sirtet** [comment]
Yes. Updating the module removed the error.
But it's not really working. With marked text somewhere, i never get any reaction,
withoult anything marked, i sometimes get the popup asking for a string, but mostly not.
Seems erratic as to when it works, i see no pattern.
Also, when i got the prompt and translate, whichever direction, the answer is always just the input, no translation...
[EDIT]
Ah, i think i found the pattern. With the defauld RAlt nothing happens.
With Lalt, EN-DE works. but when you try to quit with enter or esc. it executes DE-EN which returns the original if no translation was found... (i would expect an error, maybe the api gives none?)
Also, i noticed i could have the same hotkey for both directions, without getting a warning about it.
First i thought this triggered the double execution, but no, it happens with different hotkeys too...
