### ISSUE TITLE
Double Plural-s in debug output window

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2#192]
Hotkeyss vs.
Hotkeys

`INFO:keyboard_base:Possible collisions with a2 Hotkeyss:`

The code is here:

https://github.com/ewerybody/a2/search?q=Possible+collisions+with&unscoped_q=Possible+collisions+with

Looks like just one stray ´s´ char, or is this is meant to be a plural formatting thing?

**Comment by ewerybody** [comment]
Thanks! Nice find!
This was just a temporary function from the development of this widget. Actually... I'll just deactivate it as the widget is already showing the collisions for real.
