### ISSUE TITLE
A2 not found by windows start menu search

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2#194]
With ac'tivaid, i can start typing ac... and it shows up as app to start/open.
This does not work with A2.
Would be cool if it did.

**Comment by ewerybody** [comment]
Ah yes nice one!
I never thought about it yet. But yeah we can do that of course.
thanks :)

**Comment by ewerybody** [comment]
I just made some changes to the settings tab, putting all "integration" specific things into one handler object. [see](https://github.com/ewerybody/a2/blob/master/ui/a2widget/a2settings_view.py#L317).

This will probably also take care of the Uninstaller (#187) integration and the Start Menu items.

After all: I don't know if everybody actually **wants** this!?

IMHO: Sure I might be a little picky about this but I'd want an app to have a footprint as small as possible on my computer. Stuffing things in all locations possible is a nasty standard behavior.

**Comment by ewerybody** [comment]
Voilà! ✅
![image](https://user-images.githubusercontent.com/218956/87551703-072b2300-c6b1-11ea-9825-2ae869b6c521.png)
![image](https://user-images.githubusercontent.com/218956/87551762-18742f80-c6b1-11ea-8434-74ec0c4e48ed.png)
