### ISSUE TITLE
"Check for Updates" not working for local repositories

### ISSUE THREAD

**Issue by koppor** [ewerybody/a2#196]
### Expected Behavior

If I press "Check for  Updates" at a local repository, it should reload the repository (without checking for versions; just reload everything)

### Current Behavior

![no-update-possible](https://user-images.githubusercontent.com/1366654/77797444-5b15eb80-7071-11ea-93f4-125bcb687cab.gif)

### Possible Solution

a2 should internally remove the repository (without deleting it on the file system) -- and add it aferwards. 

### Steps to Reproduce (for bugs)

1. Create local repository
2. Add something from `a2.modules`
3. Click on "Check for Updates"
4. See that the new module doe snot appear

### Context

I want to create an own module. I want to test the module before submitting a PR to a2.modules (refs https://github.com/ewerybody/a2.modules/pull/27).

### Your Environment

* Version used: 0.0.6
* Environment name and version (e.g. Python 2.7): the one shipped with a2
* Operating System and version (desktop or mobile): Desktop

**Comment by ewerybody** [comment]
Hmmm... Well, the `Check For Updates` is specifically intended for remote repositories! 

Refreshing the ui with changes in a local one should be done just by hitting <kbd>F5</kbd>! If that doesn't help or something is broken/missing: We need to fix it there. I don't think this button is a good spot for this kind of development tool.

**Comment by koppor** [comment]
Maybe, the `Check For Updates` button can be removed then? It could also help to make the behavior dependeing on local/remote repository.

**Comment by ewerybody** [comment]
@koppor Hey! I'm just stumbling across this again... Now: How do we determine what's a local and what's a remote module package? If there is a `.git` folder in its root? Could also be that the repository just comes from somewhere else! 🤷‍♀️

I mean that's a start! I'll definitely will create a dialog to help making releases for GitHub-based module sources.

**Comment by koppor** [comment]
Maybe, I just did not understand how the local repositories work. I thought, I can just add a folder and it's a local repository. And that remote repositories are added by a URL (and not by a folder).

Maybe, my wish that the module should be reloaded if no update URL is availble is still valid? With that, I can change a plugin locally and try it out (nearly) instantly.

**Comment by ewerybody** [comment]
Well that'd be quite inconvenient to always goto the main settings, open up the module source thing and hit that button... **ac'tivAid** once had an option to reload the runtime as soon as any `.ahk` file changed! I'd like to have that back somewhen ... (* adds an issue... * #202)

For development the <kbd>F5</kbd> key is much better IMHO. Did you try? 🙂

**Comment by ewerybody** [comment]
OK. The Button now shows that there is no url available upfront.
And if there is a `.git` folder present in the package dir it will also be disabled saying that it's a dev repo 🙂
