### ISSUE TITLE
development documentation & tools

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2#2]
create a step by step list of things to do and setup like downloading tools and programs one needs to contribute to the development.
test the list.
- AHK_L
- python 3
- PySide
- Eclipse, PyDev
- git
  ...

**Comment by ewerybody** [comment]
here is a little bit:
https://github.com/ewerybody/a2/wiki/setting-you-up
still needs a comprehensive list...

**Comment by lipkau** [comment]
This could be a great topic for Ralf to get started.
As he did not work with a2 yet, he will probably notice things we take for granted.

**Comment by lipkau** [comment]
I would suggest to divide this documentations in modules:
* getting started (as a user). with links to deepdive into:
  - installing modules
  - write your own module
  - contribute to modulePacks
  - contribute to the python framework
  - anything else?

**Comment by ewerybody** [comment]
> https://github.com/ewerybody/a2/wiki/How-to-develop-a2
