### ISSUE TITLE
Portable installation

### ISSUE THREAD

**Issue by Cyberklabauter** [ewerybody/a2#206]
Will a2 be portable, like Ac'tivAid is? It would be great to see the possibility to run a2 from a USB stick - all settings saved in the program folder, leaving no traces on the system and running without admin rights. 

So far I was not abl to run a2 portable. Is there a distribution which is portable already?

**Comment by ewerybody** [comment]
Hey @Cyberklabauter ! No, currently a2 will always put its stuff into `\AppData\Local\a2`
But that folder can already be bent from there to anywhere. It's simply to have exactly 1 common ground to look for and to have nothing written to the app folder so it can be updated without interfering with the user data... 🤔 Anyway:

That's an **awesome** idea. Thanks for pointing it out!
And it can be done pretty easily. :)

**Comment by Cyberklabauter** [comment]
Great to hear that you consider to implement this. I think many ahk users use their scripts portable on a usb stick, etc.. You may consider to split it in two folders: "app" and "settings" and use a reletive path like "A_ScriptDir\..\settings\" to refer to the setting folder. Updates and the setting-backup should be easy then.

**Comment by ewerybody** [comment]
Don't worry. Thats all been settled already 😀 there are **3** folders:
* `data` - the users modules, settings and temp files
* `lib` - Autohotkey runtime, scripts and its library
* `ui` - the a2 user interface

a2 is two-fold: A runtime and a user interface for it. So there is no single app.

**Comment by Cyberklabauter** [comment]
Awesome! Looking forward to the release. 

By the way: Is there a download possibility for a compiled version. I think I found a possibility some time a go, but I do not remember the site.

**Comment by ewerybody** [comment]
Oh. there is the **Assets** thing thats collapsed on the [Releases page](https://github.com/ewerybody/a2/releases)
directly linked: https://github.com/ewerybody/a2/releases/tag/0.0.7 you see it expanded already
That should make it 🙂

**Comment by ewerybody** [comment]
ooops. I guess there is a bug that made it impossible to get packages. Will do fix asap. Hold out! ...

**Comment by Cyberklabauter** [comment]
Thank you. This helped! Downloaded the release 0.0.7 and copied the modules (version 0.5) from the old installtion. Anyways looking forward to the fix.

**Comment by ewerybody** [comment]
The UI and runtime now can work in portable mode already. things left TODO:
- [ ] make portable zip package?
- [ ] or put it all into the installer as an option?
- [ ] if portable: provide a check button for the integration options
    (since we have the getter, setter commands for these anyway we can clean things up if anything is set)

Just to be clear: In portable mode there will be nothing set into the system! right? Not even autostart.

**Comment by Cyberklabauter** [comment]
Sorry, for beeing absent and answering so late. 
1.) I personal have no preference for the distribution. A portable zip package would be fine as well as installer option. Both ways are quite common for polrtable applications. But it should not leave registry entries. More important would be, that an update function would work portable as well. 
2. Your right: In portable mode there will be nothing set into the system. But some applications provide an optional setting for autorun. (Background: Most users like me use portable apps from a USB stick or external HDD/SDD. Here you won't leave any traces on the system behind. But there are users also who uses portable apps for the ease of seeting-backup/transfer or because of the lack of rights to install programs on their system.)

**Comment by ewerybody** [comment]
> 1.) I personal have no preference for the way of distribution. A portable zip package would be fine

✔zip building is done! 

> Generally it should not leave registry entries behind. 

✔Good! The system-integration is only file based so far! No system-integration on portable mode

> More important would be, that an **update function** would work portable as well in this way.

- [ ] good point! I'll set up another issue specifically for that #209

> ... optional setting for autorun. So having the option may usefull for some users, if there is the possibility to clean things up.

❌ooohh. well... having something added to the system like autostart defeats the purpose doesn't it? I mean the current implementation does a least invasive approach anyway. Any system-integration on top of that is optional already.

And when you have a2 on the thumb drive, would you want to autostart it anyway with windows? How would we do that? 

> (Background: Most users like me use portable apps from a USB stick or external HDD/SDD. Here you won't leave any traces behind on the system. But there are users also who uses portable apps for the ease of seeting-backup/transfer or because of the lack of rights to install programs on their system.)

✔quite some time was invested to install a2 in user space only so the installer never needs to ask for elevated rights :)

**Comment by ewerybody** [comment]
@Cyberklabauter can you have a test with the latest [a2_portable_0.0.9_alpha.zip](https://github.com/ewerybody/a2/releases/download/0.0.9/a2_portable_0.0.9_alpha.zip) :)

**Comment by ewerybody** [comment]
Btw: since #182 a2 will always be portable by default. So it will look for a `data` folder in its root. This can be overridden of course :)
but some changes that were introduced due to this issue will have to be rolled back.

**Comment by Cyberklabauter** [comment]
Hi ewerybody, 

thank you soo much for your work. It looks amazing!

It is an interesting and still uncommen approach to install an app to the appdata completly. Anyways, I saw that a couple of programs (like Discord, Flux, GitHub Desktop, Slack and Google Chrome) do so as well. I wasn't aware of it. 

Testing both, portable and normal version, I can tell you that everything works fine (all configs are stored in data folder, which is in the a2 main directory) execpt one thing: After downloading modules (which works now fine as well) I don't see any module in the modul list on the right side. Also choosing a tag doensn't solve it. 

Do I something wrong?

**Comment by ewerybody** [comment]
Hey @Cyberklabauter! Hmm you'd need to enable the package as well?
![image](https://user-images.githubusercontent.com/218956/151572592-8f412728-67fe-4e69-9602-ad8415a99ed7.png)

is that it?

I'm just about making videos of the whole thing. But as I progress through my script I notice little issues on the way that i'd like to fix first :D I just need to pull through.

**Comment by Cyberklabauter** [comment]
Ahhh, sorry. I thought I did it. But I didn't do it. Stupid me. Looks fine now.

**Comment by ewerybody** [comment]
Pcheew alright! nice 👍
There is some issue with breaking downloads that I'm currently after... could also have been that one.

well. Have fun! :)
