### ISSUE TITLE
Create an organization

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2#22]
@lipkau mentioned to create an org for a2.
sadly "a2" is still a placeholder name in short for "ac'tivAid2". And a2 is taken by some dude and anything with ' inside and CamelCase AND a number...? please no.

so we need a better name! Or just an organisation name?
**a2ahk** would be free. but thats not it.

**Comment by lipkau** [comment]
I am giving this some thought. Will come back to you

**Comment by ewerybody** [comment]
Vielleicht basteln wir eher nochn bischen und dann sehen wir mal was die Leute von https://github.com/ahkscript sagen. Vielleicht kommen wir ja da unter... keine Ahnung ;] kann auch sein dass sich der Heise-Verlag wieder interessiert.

**Comment by lipkau** [comment]
ahkscript bin ich drin. Kann es jetzt schon rein nehmen ;-)

**Comment by ewerybody** [comment]
Was?! Ah sieh an! Wie das? :]

**Comment by lipkau** [comment]
Darum:
https://github.com/ahkscript/ahkscript.github.io/network/members
https://github.com/ahkscript/inviter
