### ISSUE TITLE
HotStrings - only possible to check mark

### ISSUE THREAD

**Issue by greg4b** [ewerybody/a2#232]
Steps:
installed a2 0.1.0 alpha - zip file
loaded modules
selected HotStrings

Complaint:
only check mark possible - no possibility in gui to define hotstrings.

**Comment by ewerybody** [comment]
Hey @greg4b ! Thanks for the report! I'm looking into it. And True I can verify: There is an Error showing up in the Console Tab

    ERROR:a2ctrl:Draw type "a2_local_element" not supported (yet)! Module: <a2mod.Mod HotStrings at 0x135d6a27100>

I don't have this in dev tho. This needs some investigation.

**Comment by ewerybody** [comment]
Ok. Got it fixed. It was due to empty/new config. There was a spot where I expected hotstrings to be there already 🤦‍♀️
@greg4b: can you please **Check For Updates** on the a2.modules package?

**Comment by greg4b** [comment]
Thanks for reviewing this...

As you proposed, I've made the "update" - which seemed to work properly:
![grafik](https://user-images.githubusercontent.com/16733586/119365996-cd538180-bcb0-11eb-90df-6f5d4e1f2c2a.png)

It took a restart to see some changes in the Hotstrings-Module:
![grafik](https://user-images.githubusercontent.com/16733586/119366108-e8be8c80-bcb0-11eb-9c75-cffd35a12a08.png)

But I couldn't get the "Hotstrings" Feature to work...

Further I'm missing some buttons like "OK" "Cancel" "Apply" - to get input into the program.

Thanks,

Greg

**Comment by ewerybody** [comment]
Things in a2 are usually updating automatically. No need for OK, Apply.
Well, usually: I'm just about to fix something for the main a2 package: I made changes to the runtime starter and that broke in the non-dev environment :| I'm sorry

**Comment by ewerybody** [comment]
OK there is [a new patch release 0.1.1](https://github.com/ewerybody/a2/releases/tag/0.1.1)!
It's a tiny change but worth the patch!

That "It took a restart to see some changes in the Hotstrings-Module" is actually not wanted. But that's probably because there are Python Scripts in Memory from the Hotstrings editor. This goes to another issue :) #234

**Comment by greg4b** [comment]
Works! Thank you!

A small note:
![grafik](https://user-images.githubusercontent.com/16733586/119372714-ec094680-bcb7-11eb-82c2-954a5406dcb0.png)

I would consider the Import / Export in the HotStrings Section.

**Comment by ewerybody** [comment]
Hmmm.. Naah. This area is the space for ONE single Hotstring setup. I would not mix it with options for managing the whole thing. Technically this space is also deactivated when not ONE single entry from the list is selected. You could not access these then.

We could put them underneath the whole list widget but these are options that one doesn't need so often. I'd not want them to be always visible and rather have the list longer. I really think the Module menu is the perfect spot for these :)
