### ISSUE TITLE
translation. someones gotta do it.

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2#35]
So far this is english to keep off with the hassle of translation. But looking at ac'tivAid: a2 totally needs to be translated to at least german and at best offer a nice transltation framework that makes it fun and simple to translate. As well as have minumum impact on the size of the Autohotkey runtime.

ideas...
  * have a file like variables.ahk that's fed with the accordingly translated pieces
  * ...

**Comment by ewerybody** [comment]
I've made up my mind about this and I think thats super low prio. I actually wouldn't like to do it.
Having translated applications is always trouble people with german Photoshop can hardly talk to other international pros to get feedback or tips. For such a tiny app with MUCH lower user base even fewer people could talk to each other.

**Comment by lipkau** [comment]
backlog sounds great.

however: here are some links for when this becomes relevant:
[Python Documentation:  Multilingual internationalization services](https://docs.python.org/2/library/gettext.html)
[Blog Post: How to use Python's gettext](http://inventwithpython.com/blog/2014/12/20/translate-your-python-3-program-with-the-gettext-module/)
[Community ](https://weblate.org/en/)
