### ISSUE TITLE
a2 fails to launch with non default python paths

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#71]
a2 fails to launch if python is not installed in the default directory

## Expected Behavior
* a2 launches as long as python and ahk is installed on the computer

## Current Behavior
* a2 fails to launch if python is not installed in the default location

## Possible Solution
* use python from env_var _PATH_

## Steps to Reproduce (for bugs)
1. uninstall all python installations
2. install python (I am running 3.5) under C:\program files\
3. launch a2

**Comment by ewerybody** [comment]
Yeah! Thanks for the report! :D
That's right. The **target behaviour** is actually to be able to run a2 if **neither** Autohotkey **nor** Python is installed on the computer! So there will also be a working python bundle coming with a2, IF the user wants that and is not intending to install Python 3 with our dependencies.

So far: I just updated the whole init phase.
Is it possible to workaround the issue if you change the variable `a2_python` in a2 root `a2_settings.ahk`? pointing to your desired Python version?

I mean it works for me to switch between `pythonw.exe`/`python.exe`.
But as for Python 3.5 I guess I have bad news:
```
C:\Python35\Scripts>pip install PySide
Collecting PySide
  Downloading PySide-1.2.4.tar.gz (9.3MB)
    100% |################################| 9.3MB 116kB/s
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
```
So I just Installed 3.5 myself and wanted to add PySide ... :(
We probably need to go PySide 2 soon anyway.

**Comment by lipkau** [comment]
is PySide 2 not backwards compatible?

**Comment by ewerybody** [comment]
No clue so far. I'm pretty sure they broke some things. But it will probably not be hard to migrate.

**Comment by lipkau** [comment]
we... either way, I still think the PR is valid ;-)

**Comment by ewerybody** [comment]
public relations? There is no such thing as bad advertisement ...
