### ISSUE TITLE
Install module from GitHub

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#79]
### Expected Behavior

User should be able to find a module online (ie: GitHub, BitBucket) and install by inserting the url
### Possible Solution
- [x] Show UI to insert URL (should be root of repo)
- [x] generate the tarball link of repo
- [x] download tarball to temp path
- [x] extract tarball to modules folder (using 7za.exe?)
- [ ] allow to use proxy settings

**Comment by ewerybody** [comment]
Hahaa! Just added a similar issue #80 
Yea I also thought about installing a handler thing to windows. So a link `a2: ... ` or something like that could trigger the ui to open up a dialog with the url. We could also make links to a2 drag & dropable if that helps.

**Comment by ewerybody** [comment]
Well technically I was **way** faster ;] See #57 There is stuff about having module sources anywhere. I was just glad to close it because the local backend is done. Now lets add some functionality to it! :D

**Comment by ewerybody** [comment]
hmm ... We need some though about how this URL is handled. I think it might just be a path where a certain small json is located with some info about where to download a package and how to extract it (if there are folders in there, like in the github release zips)

Python has buillt-in zip support. We don't need 7zip! ;]

**Comment by lipkau** [comment]
registering a protocol for an app is simple. Can be done with this **.reg** file:
```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\a2]
@="URL:A2 Handler"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\a2\DefaultIcon]
@="calc.exe,1"

[HKEY_CLASSES_ROOT\a2\shell]

[HKEY_CLASSES_ROOT\a2\shell\open]

[HKEY_CLASSES_ROOT\a2\shell\open\command]
@="calc.exe"
```
call: `a2://foo` and the calulator will be opened

_source: [Microsoft's Developer Network](https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx)_

**Comment by lipkau** [comment]
alpha preview?

**Comment by lipkau** [comment]
requires #80

**Comment by ewerybody** [comment]
done by #80 proxy stuff in #81
