### ISSUE TITLE
finish module source functionality via a2settings

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2#80]
### Expected Behavior
- [x] enable disable a module source
- [x] have the module sources listed
- [x] remove the package
- [x] see/edit info about  the module source
- [x] roll back to previous version
- [x] add/create module source
  - [x] from network
  - [x] from internet
  - [x] from github
  - [x] locally
- [x] update module source
  - [x] from network
  - [x] from internet
  - [x] from github
  - [x] .. and backup current version

Nice to have? necessary at all as there is a link provided?
- [ ] see/link to news about new version
- [ ] contact maintainer

**Comment by ewerybody** [comment]
for some reason I'm unable to get releases listed with the github api:

https://api.github.com/repos/ewerybody/a2.modules/releases/latest

Oh! Now it works! Maybe it doesn't if the release was flagged "pre-release"?

but listing all releases doesn't work 🤔
https://api.github.com/repos/ewerybody/a2.modules/releases

Wtf!? Now it does! :O do you have to write shit down here first?
I SWEAR it just gave me this `"message": "Not Found",` crap!!
well alright. more later...

**Comment by ewerybody** [comment]
OK I got it! a slash `/` in the end kills it!

https://api.github.com/repos/ewerybody/a2.modules/releases 👍
https://api.github.com/repos/ewerybody/a2.modules/releases/ 👎

**Comment by ewerybody** [comment]
Pchew nice! I got the local network updates :]
Along with a way of backing up current versions to TEMP.
If versions exist in temp they will be prefered. This way you can roll back to a version unless you delete it from temp. Which will also be optionally available.

**Comment by lipkau** [comment]
Why temp? Why not %userprofile%\.a2 (Linux style) or %appdata%\a2 ?

**Comment by ewerybody** [comment]
Can do. I made it a **variable** on the A2Obj.paths.
I dunno its not neeeeded but its just nice to be able to roll back to a previous version if anything breaks thats why temp.

`%userprofile%` is quite a mess. I don't want to dig in there.
`LOCALAPPDATA` maybe?

**Comment by lipkau** [comment]
I prefer %AppData%, as it is more commonly used.

_Also, I already use it for some of my modules_

**Comment by ewerybody** [comment]
Buuut isn't `APPDATA` pointing to `C:\Users\{%username%}\AppData\Roaming` which means that when you login on a network this Roaming stuff is loaded to this machine?? Might be I still didn't get it right 🤔

but well thats why I prefer `LOCALAPPDATA` 😅

**Comment by ewerybody** [comment]
Lets discuss the **structure**: We would have 4 locations that store user changable data:

* **modules**/packname/modulename _- the users selection of packages and own modules_ 
* some **module_data** - _place for module files_
* **temp** - _place for package version backups, bak files, undo caches_ 
* **settings** - _the users current settings database_

I'd rather have less. Currently we also store the generated `hotstrings.ahk` file in **settings**. Actually this would be another candidate for the **module_data** storage, right?! Also the generated includes are not really "settings" so to say.

I like the idea of the packages being stored rather unchanged in the **modules** dir and have their generated data somewhere else.
Currently there are _config_backups whenever you edit a module in the interface to fight errors in parsing/storing the config jsons. These would also goto a temp then.

**Comment by lipkau** [comment]
Agreed.

**Comment by ewerybody** [comment]
OK. Yeah! What about "**data**"?

We would store everything downloaded or generated in there.
And the main app? I'd put it next to the stuff actually. It can also be updated by itself.

`...\Appdata\Local\a2:`
  * data
    * modules - _the module packages_
    * module_data - _extra data the modules need/generate_
    * includes - _generated include files_
    * tmp - _backups, caches ..._
    * a2.db - _settings database_
  * lib
  * ui

(I'm aware that I use both the terms "package" and "module source" and would rather remove the latter)

**Comment by lipkau** [comment]
I like it

**Comment by ewerybody** [comment]
Ok. this stuff is done so far. I mode the structure stuff to a new issue then :)
