### ISSUE TITLE
add proxy tab and functionality

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#81]
_This extends #79_
### Expected Behavior

User is able to save http/socks4/socks5 proxy settings in order to be able to allow a2 to access the internet when he is in an environment which requires a proxy to access the internet.
### Possible Solution
- [x] Use pythons library **requests** which supports proxies: [Requests: Proxies](http://docs.python-requests.org/en/master/user/advanced/#proxies)
- [x] Show a UI for the user to provide **proxy address** _(schema://address:port)_, **Username** _(Optional)_, **Password** _(Optional)_

_Proxy Address could be split in **protocol** (dropdown), **address**, **port**, which is most commonly used in implementations (see utorrent)_

**Comment by ewerybody** [comment]
👍

**Comment by lipkau** [comment]
Implemented in [Proxy@ol.modules](https://github.com/lipkau/ol.modules/tree/develop/Proxy)

**Comment by lipkau** [comment]
Implementation is continued in #119

**Comment by ewerybody** [comment]
We gonna have a tab in the main settings view and make sure that a2ui and ahk functions can use these.

You need to help me with testing this. Currently I have zero proxy xp :D

**Comment by lipkau** [comment]
Absolutely.
Let me know when you need testing.

Here is something to get started with:
* The UI I implemented: https://github.com/lipkau/ol.modules/tree/develop/Proxy
* How I use the proxy data for an HTTP request: https://github.com/lipkau/ol.modules/blob/develop/urlShortener/urlShortener.ahk#L89

**Comment by ewerybody** [comment]
@lipkau can you have a look at this?
![screen_47](https://user-images.githubusercontent.com/218956/54305545-d07a5f80-45c7-11e9-86bc-842624f30294.png)

**Comment by ewerybody** [comment]
I'll close this for now
