### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#83]
### Motivation
LICENSE of code must be declared.

### Options
* [ ] [MIT](http://choosealicense.com/licenses/mit)
* [ ] [Apache License 2.0](http://choosealicense.com/licenses/apache-2.0/)
* [x] [GNU GPLv3](http://choosealicense.com/licenses/gpl-3.0/)

_source: http://choosealicense.com_

**Comment by ewerybody** [comment]
True [LICENSE](https://github.com/ewerybody/a2/blob/master/LICENSE) is missing. I added one to [a2.modules](https://github.com/ewerybody/a2.modules/blob/master/LICENSE) already. But I'm actually not sure about GPL3... What do you think?

**Comment by lipkau** [comment]
I vote for GPLv3
