### ISSUE TITLE
clicking on the toolbar icon while the UI is open, reloads the UI with an empty right pane

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2#87]
![image](https://cloud.githubusercontent.com/assets/3509308/17907355/de79d60e-697b-11e6-9432-dfffc981ba64.png)

### Expected Behavior
nothing happens as window is already open

### My Environment

* Version used: Current head
* Python 3.4
* win10 64

**Comment by ewerybody** [comment]
Yea the reload functionality is a bastard child... It was once thought to be useful for the ui development and the main reason why there is a2app hosting the a2ui but it's super hard to maintain it with inherited python classes using super(). I will make it just raise the main window by default. That actually works already.

Shutting down the original a2app and letting the new one come up is rather unsupported by `siding` But I planned to rename it anyway and add this functionality.

**Comment by ewerybody** [comment]
Ok. I'd call this fixed. Further actions: #89
