### ISSUE TITLE
en-/disabling modules shows tooltip "a2 started".... better would be "module en/disabled"

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2#88]
Sure, a2 was (re-)started, but that's not really what the user needs to know.
Informing that the changes did already take effect would make more sense in my opinion.

**Comment by ewerybody** [comment]
Hmm... the tooltip is just from a usual a2 runtime restart. It's actually nothing about the interface and only thought as a placeholder until there is a better idea how to show that the runtime is up again.

I'd rather remove it and put something into the userinterface that shows the state of the a2 runtime. Maybe just show an hourglass cursor? What do you think?

If the runtime breaks somehow it will almost always be through the last action as there is no Apply/Übernehmen that can gather multiple settings.

**Comment by sirtet** [comment]
Yes, i also thought it could just bei removed.
Not having an apply Button is obvious enough to See that it's applied. EG. Mac OS settings are like that.

**Comment by ewerybody** [comment]
There is actually already an option for that! :DWell, it't not exposed to the ui yet but I can do that soon. 
So in `a2_settings.ahk`: changing the line `a2_startup_tool_tips := true` to:

    a2_startup_tool_tips := false

will disable these tooltips.

**Comment by ewerybody** [comment]
implemented via #38
