### ISSUE TITLE
Go PySide2 🚀

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#94]
### Expected Behavior

I bid to make a2 compatible with Python 3.5 or greater
### Current Behavior

a2 only works with Python 3.0 to 3.4
### Possible Solution
- [x] Update to PySide 2
- [ ] migrte to Tkinter
- [ ] migrate to PyGObject

**Comment by ewerybody** [comment]
a2 was never written with Python 2.x! There was a time when it ran but I doubt it actually does now (I make vast use of the items() dictionary iterator which is named iteritems() in 2.x.)

**Comment by ewerybody** [comment]
What is Tkinter? And what's PyGObject? Why would that be an option?

**Comment by lipkau** [comment]
edited.
better? ;-)

they are GUI libraries.

I believe `pip install six` would make .items() work in 2.7 --> but I did not test it

**Comment by ewerybody** [comment]
Do you have any idea how much Qt code is in this project? I feel almost insulted for the suggestion to consider another ui lib! It'll be PySide2 and nothing else!

**Comment by lipkau** [comment]
so deciding how to solve this was easy. 
I am reading about PySide 2. I am very curiouse about how much of it is already working.

at least Qt got involved in the porting this year. things are going much faster

**Comment by ewerybody** [comment]
Yea we are working with Qt5 here already and the guys are building PySide2 freshly to use it. Seems it's actually the current official way to get it.

Maybe I can get a build and try a2 on it. Might even be, that there is no change needed to make it run.

So the options are:
* [ ] [set up to build PySide2 ourselves](https://wiki.qt.io/PySide2_GettingStarted)
* [ ] [go and fix the bug that keeps PySide2 building on 3.4](https://bugreports.qt.io/browse/PYSIDE-223)
* [ ] [go and fix the bug that keeps PySide building on 3.5](https://github.com/PySide/pyside-setup/issues/53) (I actually created the report in Sep 2015! 😄)
* [x] just keep using 3.4 + PySide and wait for PySide2 to work on 3.5

Currently I don't see any benefit from having 3.5 and no problems using 3.4. "It's not the latest" does not seem crucial at the time.

**Comment by ewerybody** [comment]
- [ ] wait for someone else to built binaries for Python 3.6 for PySide2 on Qt5.9:
https://stackoverflow.com/a/44672926/469322

this https://github.com/fredrikaverpil/pyside2-wheels/issues/69 is also crucial!

**Comment by ewerybody** [comment]
http://blog.qt.io/blog/2018/06/13/qt-python-5-11-released

**Comment by ewerybody** [comment]
Alright! I created a branch to test all this, wrote a converter script and it finally popped up already 😃
There are some things breaking still but its not far I guess.
