### ISSUE TITLE
Error when opening UI form traymenu

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#96]
### Current Behavior
When clicking on the "open a2 user interface" item from the tray menu, the following error is shown:
> ---------------------------
> a2app: Error on "init_a2_win()"!
> ---------------------------
> Could not call A2Window! Error:
> 'NoneType' object has no attribute 'startswith'
> Traceback:Traceback (most recent call last):
>   File "a2app.py", line 56, in init_a2_win
>     a2core._dbCleanup()
>   File "C:\Users\olive_000\Projects\a2\ui\a2core.py", line 323, in _dbCleanup
>     if not enabled.startswith('{'):
> AttributeError: 'NoneType' object has no attribute 'startswith'
> 
> Press Ctrl+C to copy this message.
> `---------------------------`
> OK   
> `---------------------------`

### Your Environment
* Version used: 185400e568d737751831f1c7326c235691f6e7fe
* Environment name and version (e.g. Python 2.7): Python 3.4
* Operating System and version (desktop or mobile): Win10

**Comment by ewerybody** [comment]
Whow. Hard to repro. Doesn't even happen when you delete the db. Well I think that does it.
